version: '3.8'

services:
  app:
    build: .
    ports:
      - '8081:8080'
    environment:
      - DATABASE_URL=postgresql+psycopg://freevents:password@db:5432/freevents
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=freevents
      - POSTGRES_USER=freevents
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
